_BASE_: Base-SBS.yml

MODEL:
  META_ARCHITECTURE: RESL

  FREEZE_LAYERS: [backbone, b1, b2, b3,]

  BACKBONE:
    WITH_NL: False

SOLVER:
  AMP:
    ENABLED: FALSE
  OPT: Adam
  MAX_EPOCH: 60
  BASE_LR: 0.00035
  WEIGHT_DECAY: 0.0005
  IMS_PER_BATCH: 64

INPUT:
  SIZE_TRAIN: [ 256, 128 ]
  SIZE_TEST: [ 256, 128 ]

  # HEADS:
  #   EMBEDDING_DIM: 2048
